### ISSUE TITLE
Possible confusion involving template re-compilation

### ISSUE THREAD

**Issue by Rob-pw** [soundstep/soma-template#19]
http://plnkr.co/edit/wsADmQWYGxaXQZSv5lfx?p=preview

The above plnkr demonstrates a situation that caught me out when writing a self-compiling template, not sure if it's worth adding a note to http://soundstep.github.io/soma-template/#re-compile, pointing out that the scope is recreated upon compilation (thus re-assignments are required).

**Comment by soundstep** [comment]
What you are showing is a a javascript reference problem, not really related to soma-template. You could have this problem with anything.

The doc is not that clear about the scope re-created though, I will add a note.

Cheers.

**Comment by Rob-pw** [comment]
Absolutely, not a 'problem' in any regard, just a point to be aware of. 

Thanks.
