### ISSUE TITLE
Template constructor, named variables not honored

### ISSUE THREAD

**Issue by Rob-pw** [soundstep/soma-template#22]
http://plnkr.co/edit/vXkEq5K2bxKjSOJ1PE9i?p=preview

Generally in soma named variables in constructors are assigned to their associated variables, rather than being assigned based on order. I incorrectly assumed this would be the case with instantiating templates. 

I think it would be nice to bring this in-line with how constructors behave elsewhere.

You may be aware of this point, I just wished to bring it your attention as it can be the cause of unexpected behaviour.

**Comment by soundstep** [comment]
This is not an issue. soma.js has dependency injection, which makes you able to create mapping injection names and use them in constructor. soma-template doesn't and It will never have infuse.js included in it.
