### ISSUE TITLE
soma-template swallowing errors in services, templates

### ISSUE THREAD

**Issue by Rob-pw** [soundstep/soma-template#23]
https://github.com/soundstep/soma-template/blob/cf7d4a7ab06b9d303c89d7145c4352ccfe308777/src/12.bootstrap.js#L21

Without any sort of logging on this line, or re-throwing the error, when a template encounters an error it does so quietly, which causes problems identifying the offending code without placing breakpoints at strategic positions.

**Comment by soundstep** [comment]
I agree, not a good thing. Can you do a pull request if possible? I would probably just remove the try catch.

**Comment by soundstep** [comment]
I'll do it, got a couple of minutes :D
