### ISSUE TITLE
Make the docs more clear about the use of npm install

### ISSUE THREAD

**Issue by motatoes** [soundstep/soma-template#27]
I think there is a missing point about the use of `soma-template` when installing with `npm install`. To make it properly work I had to do the [following](http://stackoverflow.com/a/36445873)

    var soma = require('soma.js');
    var template = require('soma-template');
    soma.plugins.add(template.Plugin);

However, only the second line is included in the [docs](http://soundstep.github.io/soma-template/#download). I think all 3 should be included for clarity (happy to do a PR if needed).

**Comment by soundstep** [comment]
Hi there,
I don't mention soma.js because the template library is completely separate and can work on its own.
You also don't need to when loading it in the brpwser: http://somajs.github.io/somajs/site/#load-template-plugin
But I'll find a place to make more obvious.
Cheers.

**Comment by soundstep** [comment]
I've added documentation there: 
http://somajs.github.io/somajs/site/#template
Thanks for reporting.
